# SPDX-FileCopyrightText: 2024 Johann Klähn <johann@jklaehn.de>
#
# SPDX-License-Identifier: MIT

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.5
  hooks: [id: clang-format]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  - id: ruff
  - id: ruff-format
  - id: ruff-format
    types: [file]
    types_or: [file]
    files: lit\.cfg$
- repo: https://github.com/fsfe/reuse-tool
  rev: v5.0.2
  hooks: [id: reuse-lint-file]
