# SPDX-FileCopyrightText: 2024 Johann Klähn <johann@jklaehn.de>
#
# SPDX-License-Identifier: MIT

name: Build + Tests
on:
  push: {branches: [main]}
  pull_request: {branches: [main]}
  workflow_dispatch: {}

env:
  BUILD_TYPE: Debug
  BUILD_DEPENDENCIES: >-
    clang-devel
    cmake
    gmock-devel
    gtest-devel
    llvm-devel
    ninja-build
    python
    pybind11-devel
    python3-devel
    python3-pip

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Install dependencies
        run: |
          dnf install -y ${{ env.BUILD_DEPENDENCIES }}

      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure
        run: |
          cmake -B "${{ github.workspace }}/build" -DCMAKE_BUILD_TYPE="${{ env.BUILD_TYPE }}"

      - name: Build
        run: |
          cmake --build "${{ github.workspace }}/build"

      - name: Test
        run: |
          export PYTHONPATH="${{ github.workspace }}/build"
          cmake --build "${{ github.workspace }}/build" --target test
